/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kewenc_kewenclame_MainActivity */

#ifndef _Included_com_kewenc_kewenclame_MainActivity
#define _Included_com_kewenc_kewenclame_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kewenc_kewenclame_MainActivity
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kewenc_kewenclame_MainActivity_convertmp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_kewenc_kewenclame_MainActivity
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kewenc_kewenclame_MainActivity_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
